-- return {
--   'lervag/vimtex',
--   lazy = false, -- we don't want to lazy load VimTeX
--   -- tag = "v2.15", -- uncomment to pin to a specific release
--   init = function()
--     -- VimTeX configuration goes here
--     vim.cmd [[
--     syntax enable
--     " Viewer options: One may configure the viewer either by specifying a built-in
--     " viewer method:
--     let g:vimtex_view_method = 'zathura'
--     let g:vimtex_compiler_method = 'latexrun'
--     " Most VimTeX mappings rely on localleader and this can be changed with the
--     " following line. The default is usually fine and is the symbol "\".
-- ]]
--   end,
-- }
--
return {}
